// Auto-generated by scripts/sync-daily-briefs.cjs
// ⚠️ 此文件由构建脚本自动生成，请勿手动修改

export interface DailyBrief {
  date: string;
  title: string;
  file: string;
  displayDate: string;
}

export const dailyBriefs: DailyBrief[] = [
  {
    "date": "2026-04-13",
    "title": "2026年4月13日 周一 今日速览",
    "file": "每日早参/article_20260413.html",
    "displayDate": "4月13日 周一"
  }
];
